name: librarian
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  avatar_glow: ^2.0.2
  cloud_firestore: 3.1.10
  convex_bottom_bar: ^3.0.0
  convex_bottom_navigation: ^1.1.1
  cupertino_icons: ^1.0.2
  dropdown_search: ^2.0.1
  file_picker: 4.4.0
  firebase_auth: 3.3.9
  firebase_core: 1.13.1
  firebase_storage: 10.2.9
  flutter_native_splash: 2.1.0
  get: 4.6.1
  image_picker: 0.8.4+10
  intl: ^0.17.0
  introduction_screen: ^3.0.0
  lottie: ^1.2.2
  nb_utils: 4.4.12
  cached_network_image: 3.2.0
  badges: 2.0.2
  flutter_svg: 1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/lottie/
    - assets/
  uses-material-design: true

flutter_icons:
  android: launcher_icon
  image_path: assets/icon.png
  ios: true

flutter_native_splash:
  color: "#650aab"
